### PR TITLE
Integrated phenolib storage

### LINKED ISSUE #115: In Storage migrator, if root folder selected, create <appName> primary folder
Tested on Android 9 Lenovo Tab 4 8

### PR DESCRIPTION
**Pull request by chaneylc**
Added generic phenolib storage.
Fixes #115

### CODE REVIEW

**Comment by trife** [comment]
@chaneylc Why are the Define/Migrate/Skip buttons so much thinner in this implementation? I looked at the styles but didn't see any major reason for it here versus Coordinate/Field Book. I think I prefer white background and primaryColor for buttons in the definer fragment.

**Comment by chaneylc** [comment]
The app themes are different, Coordinate/FB use AppCompat, Prospector uses MaterialComponents. I updated the style for definer/migrator to use AppCompat.

**Comment by trife** [comment]
- @chaneylc when searching to identify if new folders should be created, we should ignore case. The folder I had been using had a `Database` folder and selecting the same folder for storage a few times has resulted in `database (1)`, `database (2)`, etc.

**Comment by chaneylc** [comment]
Yeah I have ran into that issue before. I think there is something odd with DocumentFile where their createFile(name) will ignore case, but their findFile(name) will not. I'll add a fix for this in phenolib, but might also need to investigate further to see if this is a bug.

**Pull request merged**
